---
# auto-reload when files change
watch:
  - src
  - .trmnlp.yml

# values of custom fields (defined in src/settings.yml)
custom_fields:
  user_token: user_8ax7n7szxor3jo3hqw8mk96v
  plugin_id: '216968'

# Time zone IANA identifier
time_zone: Asia/Dubai